[project]
name = "agogos"
version = "0.0.2"
authors = [
    { name = "Jasper van Selm", email = "jmvanselm@gmail.com" },
]
description = "This package contains the code for creating a ml pipeline"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies= [
    # data manipulation
    "numpy>=1.26.2",

    # hashing
    "joblib==1.3.2"
]
